#PostgreSQL DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
spring.datasource.username=postgres
spring.datasource.password=1234

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional: format SQL in logs
spring.jpa.properties.hibernate.format_sql=trueand 